# include this file which comes with go installation
include ${GOROOT}/src/Make.inc 

TARG=mylibpkg

# the *_test.go files are not to be included here. Only those your would use to build the actual program.  go test will figure out the *_test.go files for itself.
GOFILES=\
common.go\
stack_slice.go\
stack_csp.go\
stack.go\
stack_sync.go\

# include this file which comes with go installation
include ${GOROOT}/src/Make.pkg
